.definitions: 
  cache: &composer-cache
    key:
      files:
        - composer.lock
    paths:
      - vendor/

stages:
  - test

test:phpunit:
  cache: *composer-cache
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/phpunit --do-not-cache-result --log-junit phpunit-report.xml --coverage-cobertura phpunit-coverage.xml --coverage-text --colors=never
  artifacts:
    when: always
    reports:
      junit: phpunit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunit-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

test:infection:
  cache: *composer-cache
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/infection -n -jmax
  artifacts:
    when: always
    reports:
      codequality: build/infection/gitlab-coverage.json

test:phpstan:
  cache: *composer-cache
  image: 
    name: ghcr.io/phpstan/phpstan:2-php8.3
    entrypoint: [""]
  script:
    - phpstan analyse --no-progress --error-format gitlab > phpstan.json
  artifacts:
    when: always
    reports:
      codequality: phpstan.json

test:composer-dependency-analyser:
  cache: *composer-cache
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/composer-dependency-analyser --format junit > composer-dependency.json
  artifacts:
    when: always
    reports:
      junit: composer-dependency.json

test:php-cs-fixer:
  cache: *composer-cache
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/php-cs-fixer fix -v --dry-run --format=gitlab --using-cache=no src/ > gl-cs-fixer.json || exit 0
  artifacts:
    reports:
      codequality: gl-cs-fixer.json
