.composer-cache: &composer-cache
  key:
    files:
      - composer.lock
  paths:
    - vendor/
  policy: pull

stages:
  - prepare
  - test
  - publish

prepare:composer-cache:
  stage: prepare
  dependencies: []
  cache:
    - <<: *composer-cache
      policy: pull-push
  image: sineverba/php8xc:latest
  script:
    - composer install
  only:
    changes:
      - composer.lock

test:phpunit_8.1:
  stage: test
  cache: *composer-cache
  dependencies: []
  image: sineverba/php8xc:1.11.0
  before_script:
    - composer install
  script:
    - php vendor/bin/phpunit --do-not-cache-result

test:phpunit_8.3:
  stage: test
  cache: *composer-cache
  dependencies: []
  image: sineverba/php8xc:1.18.0
  before_script:
    - composer install
  script:
    - vendor/bin/phpunit --do-not-cache-result --log-junit phpunit-report.xml --coverage-cobertura phpunit-coverage.xml --coverage-text --colors=never
  artifacts:
    when: always
    reports:
      junit: phpunit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunit-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

test:infection:
  stage: test
  cache: *composer-cache
  dependencies: []
  needs: ["test:phpunit_8.3"]
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/infection -n -jmax
  artifacts:
    when: always
    reports:
      codequality: build/infection/gitlab-coverage.json

test:phpstan:
  stage: test
  cache: *composer-cache
  dependencies: []
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/phpstan analyse --no-progress --error-format gitlab > phpstan.json
  artifacts:
    when: always
    reports:
      codequality: phpstan.json

test:composer-dependency-analyser:
  stage: test
  cache: *composer-cache
  dependencies: []
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/composer-dependency-analyser --format junit > composer-dependency.json
  artifacts:
    when: always
    reports:
      junit: composer-dependency.json

test:php-cs-fixer:
  stage: test
  cache: *composer-cache
  dependencies: []
  image: sineverba/php8xc:1.18.0
  before_script:
    - composer install
  script:
    - vendor/bin/php-cs-fixer fix -v --dry-run --format=gitlab --using-cache=no src/ > gl-cs-fixer.json
  artifacts:
    reports:
      codequality: gl-cs-fixer.json
  allow_failure: true

test:phpmd:
  stage: test
  cache: *composer-cache
  dependencies: []
  image: sineverba/php8xc:latest
  before_script:
    - composer install
  script:
    - vendor/bin/phpmd src,tests gitlab rulesets.xml --report-file codeclimate-report.json
  artifacts:
    reports:
      codequality: codeclimate-report.json
  allow_failure: true
include:
  - component: $CI_SERVER_FQDN/components/sast/sast@2.1.0
  - component: $CI_SERVER_FQDN/components/secret-detection/secret-detection@1.1.2
  - component: $CI_SERVER_FQDN/base-ci-components/php/gitlab-ci-phpdocumentator@v1.0.2
